/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'language' : IDL.Text,
  'schedule' : IDL.Text,
  'enrollmentOpen' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([Course], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'body' : IDL.Text,
          'date' : IDL.Int,
          'language' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'timestamp' : IDL.Int,
            'phone' : IDL.Text,
            'course' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllContactMessages' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'subject' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'timestamp' : IDL.Int,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllDonations' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'donorName' : IDL.Text,
            'email' : IDL.Text,
            'currency' : IDL.Text,
            'timestamp' : IDL.Int,
            'amount' : IDL.Int,
            'purpose' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllEnrollments' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'studentName' : IDL.Text,
            'plan' : IDL.Text,
            'email' : IDL.Text,
            'currency' : IDL.Text,
            'timestamp' : IDL.Int,
            'courseId' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'title' : IDL.Text,
            'body' : IDL.Text,
            'date' : IDL.Int,
            'language' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseLiveStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool))],
      ['query'],
    ),
  'getCourseLiveStatusFor' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordDonation' : IDL.Func(
      [
        IDL.Record({
          'donorName' : IDL.Text,
          'email' : IDL.Text,
          'currency' : IDL.Text,
          'timestamp' : IDL.Int,
          'amount' : IDL.Int,
          'purpose' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'recordEnrollment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'setCourseLive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnouncement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'title' : IDL.Text,
          'body' : IDL.Text,
          'date' : IDL.Int,
          'language' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'updateCourse' : IDL.Func([Course], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'language' : IDL.Text,
    'schedule' : IDL.Text,
    'enrollmentOpen' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([Course], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'body' : IDL.Text,
            'date' : IDL.Int,
            'language' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'message' : IDL.Text,
              'timestamp' : IDL.Int,
              'phone' : IDL.Text,
              'course' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllContactMessages' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'subject' : IDL.Text,
              'name' : IDL.Text,
              'email' : IDL.Text,
              'message' : IDL.Text,
              'timestamp' : IDL.Int,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllDonations' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'donorName' : IDL.Text,
              'email' : IDL.Text,
              'currency' : IDL.Text,
              'timestamp' : IDL.Int,
              'amount' : IDL.Int,
              'purpose' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllEnrollments' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'studentName' : IDL.Text,
              'plan' : IDL.Text,
              'email' : IDL.Text,
              'currency' : IDL.Text,
              'timestamp' : IDL.Int,
              'courseId' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'title' : IDL.Text,
              'body' : IDL.Text,
              'date' : IDL.Int,
              'language' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseLiveStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Bool))],
        ['query'],
      ),
    'getCourseLiveStatusFor' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordDonation' : IDL.Func(
        [
          IDL.Record({
            'donorName' : IDL.Text,
            'email' : IDL.Text,
            'currency' : IDL.Text,
            'timestamp' : IDL.Int,
            'amount' : IDL.Int,
            'purpose' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'recordEnrollment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'setCourseLive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'title' : IDL.Text,
            'body' : IDL.Text,
            'date' : IDL.Int,
            'language' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'updateCourse' : IDL.Func([Course], [], []),
  });
};

export const init = ({ IDL }) => { return []; };